import { useEffect, useState } from 'react'
import type { KeyboardEvent, ReactNode } from 'react'
import { Check, ChevronRight, Plus, X } from 'lucide-react'
import { fetchReview, findTags, saveReview } from './review/api'
import type { ImageForReview, Tag, TagType } from './review/api'
function Header({ title, children }: { title: string; children: ReactNode }) { return <><div className="eyebrow">BLACKWING</div><h1>{title}</h1><p>{children}</p></> }
export function GalleryPage() { return <section><Header title="Gallery">Your private gallery will appear here once images are imported.</Header><div className="empty-state"><div className="empty-icon">⌑</div><h2>Your gallery is ready</h2><p>Upload images to start building your collection. Tags and filters arrive in the next product phases.</p></div></section> }
const tagTypes: { type: TagType; label: string; placeholder: string }[] = [{ type: 'Person', label: 'Person', placeholder: 'Add a person…' }, { type: 'Place', label: 'Place', placeholder: 'Add a place…' }, { type: 'Topic', label: 'Topic', placeholder: 'Add a topic…' }]
function TagEditor({ type, label, placeholder, tags, onChange }: { type: TagType; label: string; placeholder: string; tags: Tag[]; onChange: (tags: Tag[]) => void }) {
  const [input, setInput] = useState(''); const [suggestions, setSuggestions] = useState<Tag[]>([])
  useEffect(() => { const value = input.trim(); if (!value) return; const timer = window.setTimeout(() => { void findTags(type, value).then(setSuggestions) }, 180); return () => window.clearTimeout(timer) }, [input, type])
  const add = (value: string) => { const clean = value.trim(); if (!clean || tags.some(tag => tag.value.localeCompare(clean, undefined, { sensitivity: 'accent' }) === 0)) return; onChange([...tags, { id: crypto.randomUUID(), type, value: clean }]); setInput(''); setSuggestions([]) }
  const keyDown = (event: KeyboardEvent<HTMLInputElement>) => { if (event.key === 'Enter') { event.preventDefault(); add(input) } }
  return <div className={`tag-editor tag-${type.toLowerCase()}`}><div className="tag-title"><span /><strong>{label}</strong></div><div className="tag-chips">{tags.map(tag => <span className="tag-chip" key={tag.id}>{tag.value}<button onClick={() => onChange(tags.filter(item => item.id !== tag.id))} aria-label={`Remove ${tag.value}`}><X size={13} /></button></span>)}</div><div className="tag-entry"><input value={input} onChange={event => { setInput(event.target.value); if (!event.target.value.trim()) setSuggestions([]) }} onKeyDown={keyDown} placeholder={placeholder} maxLength={128} /><button className="add-tag" onClick={() => add(input)} title={`Add ${label}`}><Plus size={16} /></button>{input.trim() && suggestions.length > 0 && <div className="tag-suggestions">{suggestions.map(tag => <button key={tag.id} onMouseDown={event => { event.preventDefault(); add(tag.value) }}>{tag.value}</button>)}</div>}</div></div>
}
export function ReviewPage() {
  const [data, setData] = useState<{ pendingCount: number; image: ImageForReview | null } | null>(null); const [tags, setTags] = useState<Tag[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const load = () => fetchReview().then(result => { setData(result); setTags(result.image?.tags ?? []); setError('') }).catch(reason => setError(reason instanceof Error ? reason.message : 'Could not load the review queue.'))
  useEffect(() => { void load() }, [])
  const save = async () => { if (!data?.image) return; setSaving(true); try { await saveReview(data.image.id, tags); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save the review.') } finally { setSaving(false) } }
  if (!data) return <section><Header title="Pending review">Assign tags one image at a time, then move to the next.</Header><p className="loading">Loading review queue…</p></section>
  if (!data.image) return <section><Header title="Pending review">Assign tags one image at a time, then move to the next.</Header><div className="empty-state"><div className="empty-icon success">✓</div><h2>You&apos;re all caught up</h2><p>New uploads will appear here for review.</p></div></section>
  const image = data.image
  return <section className="review-page"><div className="eyebrow">PENDING REVIEW · {data.pendingCount} LEFT</div><h1>Review image</h1><p>Assign tags, or simply mark it reviewed when there is nothing to add.</p>{error && <p role="alert" className="form-error">{error}</p>}<div className="review-layout"><div className="review-preview"><img src={`/api/images/${image.id}/preview`} alt="Image waiting for review" /><dl><div><dt>Uploaded</dt><dd>{new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(image.uploadedAt))}</dd></div><div><dt>Dimensions</dt><dd>{image.width} × {image.height}</dd></div></dl></div><div className="review-form">{tagTypes.map(config => <TagEditor key={config.type} {...config} tags={tags.filter(tag => tag.type === config.type)} onChange={next => setTags(current => [...current.filter(tag => tag.type !== config.type), ...next])} />)}<button className="review-submit" disabled={saving} onClick={() => void save()}><Check size={18} />{saving ? 'Saving…' : 'Mark reviewed & next'}<ChevronRight size={17} /></button></div></div></section>
}
export { UploadPage } from './upload/UploadPage'
