// <auto-generated />
using System;
using Belfalas.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Belfalas.Persistence.Migrations
{
    [DbContext(typeof(BelfalasDbContext))]
    [Migration("20260627141100_InitialDomainModel")]
    partial class InitialDomainModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Belfalas.Domain.ArchivedEra", b =>
                {
                    b.Property<Guid>("EraId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Snapshot")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("TEXT");

                    b.HasKey("EraId");

                    b.ToTable("archived_eras", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DistrictId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("EraId", "Order");

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.AreaProgress", b =>
                {
                    b.Property<Guid>("AreaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EraId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("AreaId");

                    b.HasIndex("EraId");

                    b.ToTable("area_progresses", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.BuiltPlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EraId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlotId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlotId");

                    b.HasIndex("VariantId");

                    b.HasIndex("EraId", "PlotId")
                        .IsUnique();

                    b.ToTable("built_plots", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.DailyCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DailyHabitId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EraId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DailyHabitId");

                    b.HasIndex("EraId", "Date", "DailyHabitId")
                        .IsUnique();

                    b.ToTable("daily_completions", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.DailyHabit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("EraId");

                    b.ToTable("daily_habits", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.DenizenCount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DenizenType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EraId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("EraId", "DistrictId", "DenizenType")
                        .IsUnique();

                    b.ToTable("denizen_counts", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorldTemplateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorldTemplateId", "Slot")
                        .IsUnique();

                    b.ToTable("districts", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.Era", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Weeks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorldTemplateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorldTemplateId");

                    b.ToTable("eras", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.EvolutionStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DenizenType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId", "Order")
                        .IsUnique();

                    b.ToTable("evolution_stages", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.Plot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId", "PositionX", "PositionY")
                        .IsUnique();

                    b.ToTable("plots", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.Variant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpriteKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorldTemplateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorldTemplateId", "Category");

                    b.ToTable("variants", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.WeeklyCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EraId")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WeeklyGoalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyGoalId");

                    b.HasIndex("EraId", "WeekIndex", "WeeklyGoalId")
                        .IsUnique();

                    b.ToTable("weekly_completions", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.WeeklyGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("EraId");

                    b.ToTable("weekly_goals", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.WeeklySet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EraId")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeekIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EraId", "WeekIndex")
                        .IsUnique();

                    b.ToTable("weekly_sets", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.WeeklySetItem", b =>
                {
                    b.Property<Guid>("WeeklySetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WeeklyGoalId")
                        .HasColumnType("TEXT");

                    b.HasKey("WeeklySetId", "WeeklyGoalId");

                    b.HasIndex("WeeklyGoalId");

                    b.ToTable("weekly_set_items", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.WorldTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("world_templates", (string)null);
                });

            modelBuilder.Entity("Belfalas.Domain.ArchivedEra", b =>
                {
                    b.HasOne("Belfalas.Domain.Era", "Era")
                        .WithMany()
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Era");
                });

            modelBuilder.Entity("Belfalas.Domain.Area", b =>
                {
                    b.HasOne("Belfalas.Domain.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Belfalas.Domain.Era", "Era")
                        .WithMany("Areas")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Era");
                });

            modelBuilder.Entity("Belfalas.Domain.AreaProgress", b =>
                {
                    b.HasOne("Belfalas.Domain.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Belfalas.Domain.Era", "Era")
                        .WithMany()
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Era");
                });

            modelBuilder.Entity("Belfalas.Domain.BuiltPlot", b =>
                {
                    b.HasOne("Belfalas.Domain.Era", "Era")
                        .WithMany()
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Belfalas.Domain.Plot", "Plot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Belfalas.Domain.Variant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Era");

                    b.Navigation("Plot");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Belfalas.Domain.DailyCompletion", b =>
                {
                    b.HasOne("Belfalas.Domain.DailyHabit", "DailyHabit")
                        .WithMany()
                        .HasForeignKey("DailyHabitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Belfalas.Domain.Era", "Era")
                        .WithMany()
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyHabit");

                    b.Navigation("Era");
                });

            modelBuilder.Entity("Belfalas.Domain.DailyHabit", b =>
                {
                    b.HasOne("Belfalas.Domain.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Belfalas.Domain.Era", "Era")
                        .WithMany("DailyHabits")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Era");
                });

            modelBuilder.Entity("Belfalas.Domain.DenizenCount", b =>
                {
                    b.HasOne("Belfalas.Domain.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Belfalas.Domain.Era", "Era")
                        .WithMany()
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Era");
                });

            modelBuilder.Entity("Belfalas.Domain.District", b =>
                {
                    b.HasOne("Belfalas.Domain.WorldTemplate", "WorldTemplate")
                        .WithMany("Districts")
                        .HasForeignKey("WorldTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorldTemplate");
                });

            modelBuilder.Entity("Belfalas.Domain.Era", b =>
                {
                    b.HasOne("Belfalas.Domain.WorldTemplate", "WorldTemplate")
                        .WithMany()
                        .HasForeignKey("WorldTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorldTemplate");
                });

            modelBuilder.Entity("Belfalas.Domain.EvolutionStage", b =>
                {
                    b.HasOne("Belfalas.Domain.District", "District")
                        .WithMany("EvolutionStages")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Belfalas.Domain.Plot", b =>
                {
                    b.HasOne("Belfalas.Domain.District", "District")
                        .WithMany("Plots")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Belfalas.Domain.Variant", b =>
                {
                    b.HasOne("Belfalas.Domain.WorldTemplate", "WorldTemplate")
                        .WithMany("Variants")
                        .HasForeignKey("WorldTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorldTemplate");
                });

            modelBuilder.Entity("Belfalas.Domain.WeeklyCompletion", b =>
                {
                    b.HasOne("Belfalas.Domain.Era", "Era")
                        .WithMany()
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Belfalas.Domain.WeeklyGoal", "WeeklyGoal")
                        .WithMany()
                        .HasForeignKey("WeeklyGoalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Era");

                    b.Navigation("WeeklyGoal");
                });

            modelBuilder.Entity("Belfalas.Domain.WeeklyGoal", b =>
                {
                    b.HasOne("Belfalas.Domain.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Belfalas.Domain.Era", "Era")
                        .WithMany("WeeklyGoals")
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Era");
                });

            modelBuilder.Entity("Belfalas.Domain.WeeklySet", b =>
                {
                    b.HasOne("Belfalas.Domain.Era", "Era")
                        .WithMany()
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Era");
                });

            modelBuilder.Entity("Belfalas.Domain.WeeklySetItem", b =>
                {
                    b.HasOne("Belfalas.Domain.WeeklyGoal", "WeeklyGoal")
                        .WithMany()
                        .HasForeignKey("WeeklyGoalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Belfalas.Domain.WeeklySet", "WeeklySet")
                        .WithMany("Items")
                        .HasForeignKey("WeeklySetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklyGoal");

                    b.Navigation("WeeklySet");
                });

            modelBuilder.Entity("Belfalas.Domain.District", b =>
                {
                    b.Navigation("EvolutionStages");

                    b.Navigation("Plots");
                });

            modelBuilder.Entity("Belfalas.Domain.Era", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("DailyHabits");

                    b.Navigation("WeeklyGoals");
                });

            modelBuilder.Entity("Belfalas.Domain.WeeklySet", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Belfalas.Domain.WorldTemplate", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
