import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Aperture, ClipboardCheck, Image, LogOut, UploadCloud, Users } from 'lucide-react'
import { BrowserRouter, Navigate, NavLink, Route, Routes } from 'react-router-dom'
import { DetailPage, GalleryPage, ReviewPage, UploadPage } from '@/features/pages'
type CurrentUser = { id: string; username: string; roles: string[] }
async function csrf() { return (await (await fetch('/api/auth/antiforgery')).json()).requestToken as string }
function Login({ onSignedIn }: { onSignedIn: (user: CurrentUser) => void }) { const [error, setError] = useState(''); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); const response = await fetch('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': await csrf() }, body: JSON.stringify({ username: data.get('username'), password: data.get('password') }) }); if (!response.ok) return setError('Invalid username or password.'); onSignedIn(await (await fetch('/api/auth/me')).json()) } return <main className="login-page"><form className="login-card" onSubmit={submit}><div className="brand"><span className="brand-mark"><Aperture size={24} /></span><span>Blackwing</span></div><div><div className="eyebrow">SIGN IN</div><h1>Welcome back</h1><p>Sign in to browse, upload and tag your private image gallery.</p></div><label>Username<input name="username" required autoComplete="username" /></label><label>Password<input name="password" type="password" required minLength={12} autoComplete="current-password" /></label>{error && <p role="alert" className="form-error">{error}</p>}<button className="button">Sign in</button><p className="hint">Forgot your password? Ask an admin to reset it.</p></form></main> }
function AdminPage() { return <section><div className="eyebrow">BLACKWING</div><h1>Manage accounts</h1><p>Create local accounts and reset passwords. Gallery content is never available to administrators.</p></section> }
function Shell({ user, signOut }: { user: CurrentUser; signOut: () => void }) { const admin = user.roles.includes('Admin'); const navigation = admin ? [{ to: '/admin', label: 'Manage accounts', icon: Users }] : [{ to: '/gallery', label: 'Gallery', icon: Image }, { to: '/review', label: 'Pending review', icon: ClipboardCheck }, { to: '/upload', label: 'Upload', icon: UploadCloud }]; return <div className="application-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Aperture size={18} /></span><span>Blackwing</span></div><nav>{navigation.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}><Icon size={18} />{label}</NavLink>)}</nav><div className="sidebar-footer"><span><strong>{user.username}</strong><br />{admin ? 'Administrator' : 'User'}</span><button className="icon-button" onClick={signOut} title="Sign out"><LogOut size={17} /></button></div></aside><main className="main-content"><Routes><Route path="/gallery" element={<GalleryPage />} /><Route path="/gallery/:id" element={<DetailPage />} /><Route path="/review" element={<ReviewPage />} /><Route path="/upload" element={<UploadPage />} /><Route path="/admin" element={admin ? <AdminPage /> : <Navigate to="/gallery" replace />} /><Route path="*" element={<Navigate to={admin ? '/admin' : '/gallery'} replace />} /></Routes></main></div> }
export function App() { const [user, setUser] = useState<CurrentUser | null | undefined>(undefined); useEffect(() => { fetch('/api/auth/me').then(r => r.ok ? r.json() : null).then(setUser).catch(() => setUser(null)) }, []); if (user === undefined) return null; return <BrowserRouter>{user ? <Shell user={user} signOut={async () => { await fetch('/api/auth/logout', { method: 'POST', headers: { 'X-CSRF-TOKEN': await csrf() } }); setUser(null) }} /> : <Login onSignedIn={setUser} />}</BrowserRouter> }
