[CmdletBinding()]
param(
    # Root folder that will hold every persistent Segaris volume as a bind mount.
    # Defaults to the OneDrive location requested for this machine.
    [string]$BasePath = "C:\Users\carlu\OneDrive\Archivos\_segaris",
    [switch]$NoBuild
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$composeDir = Join-Path $root "deploy/compose"
$baseFile = Join-Path $composeDir "docker-compose.yml"
$localFile = Join-Path $composeDir "docker-compose.local.yml"
$envFile = Join-Path $composeDir ".env"
$exampleFile = Join-Path $composeDir ".env.example"

# Build (unless -NoBuild) and start the full container stack locally with every
# persistent volume bind-mounted under $BasePath instead of Docker-managed
# volumes. This deliberately does NOT use docker-compose.windows.yml; a generated
# override (written to the temp folder) redirects all volumes to $BasePath.
#
# WARNING: $BasePath lives inside OneDrive. OneDrive will try to sync the live
# PostgreSQL data files, which can corrupt the database and generates heavy sync
# churn. Exclude (or pause syncing of) the "postgres" subfolder before relying on
# this for real data.

# --- Bootstrap the .env exactly like scripts/compose-up.ps1 -----------------
if (-not (Test-Path $envFile)) {
    Copy-Item $exampleFile $envFile
    $devPassword = "segaris-local-dev"
    (Get-Content $envFile) `
        -replace '^SEGARIS_POSTGRES_PASSWORD=.*', "SEGARIS_POSTGRES_PASSWORD=$devPassword" `
        | Set-Content $envFile
    Write-Host "Created $envFile from the example with a local development password."
    Write-Host "Review it before any non-local use; never commit it."
}

# --- Create the bind-mount directory tree under $BasePath -------------------
# One subfolder per persistent volume in the stack.
$subDirs = @(
    "postgres",              # PostgreSQL data directory
    "attachments",           # backend: /data/attachments
    "backups",               # backend: /data/backups
    "dataprotection-keys",   # backend: /data/dataprotection-keys
    "caddy/data",            # caddy: /data
    "caddy/config"           # caddy: /config
)
foreach ($sub in $subDirs) {
    $full = Join-Path $BasePath $sub
    if (-not (Test-Path $full)) {
        New-Item -ItemType Directory -Force $full | Out-Null
    }
}
Write-Host "Persistent volumes will live under: $BasePath"

# --- Generate the volume-redirect override ----------------------------------
# Docker needs forward slashes; Windows drive letters are fine in long syntax.
$dockerBase = ($BasePath -replace '\\', '/').TrimEnd('/')
$overrideFile = Join-Path $env:TEMP "segaris-compose-onedrive.yml"
$overrideContent = @"
# AUTO-GENERATED by scripts/compose-up-onedrive.ps1 - do not edit by hand.
# Redirects every Segaris volume to a bind mount under:
#   $BasePath
# Compose merges service volumes by target, so these replace the named volumes
# and bind mounts declared in docker-compose.yml.
services:
  postgres:
    volumes:
      - type: bind
        source: "$dockerBase/postgres"
        target: /var/lib/postgresql/data
  backend:
    volumes:
      - type: bind
        source: "$dockerBase/attachments"
        target: /data/attachments
      - type: bind
        source: "$dockerBase/backups"
        target: /data/backups
      - type: bind
        source: "$dockerBase/dataprotection-keys"
        target: /data/dataprotection-keys
  caddy:
    volumes:
      - type: bind
        source: "$dockerBase/caddy/data"
        target: /data
      - type: bind
        source: "$dockerBase/caddy/config"
        target: /config
"@
$overrideContent | Set-Content $overrideFile

# --- Bring the stack up -----------------------------------------------------
$arguments = @(
    "compose",
    "--env-file", $envFile,
    "--project-directory", $composeDir,
    "-f", $baseFile,
    "-f", $localFile,
    "-f", $overrideFile,
    "up", "-d"
)
if (-not $NoBuild) {
    $arguments += "--build"
}

& docker @arguments
if ($LASTEXITCODE -ne 0) {
    throw "docker compose up failed with exit code $LASTEXITCODE."
}

Write-Host "Stack is up. Open http://localhost:5525/ (or your configured SEGARIS_HTTP_PORT)."
Write-Host "Reminder: exclude '$BasePath\postgres' from OneDrive syncing to avoid database corruption."
